### ISSUE TITLE
Invalid authentication request and do not let sigin to docusign.

### ISSUE THREAD

**Issue by RaziaSandhu** [docusign/docusign-android-starter-kit#1]
![screenshot_20170629-112107](https://user-images.githubusercontent.com/28975231/27673287-749bce46-5cbd-11e7-8ddd-479dcb3be09c.png)

Can you help me please

**Comment by mmallis87** [comment]
In case you haven't made any change to the code that constructs the "authorization url", you shouldn't get this error, unless your integrator key is not well set up:

The sample app in this kit uses the standard "Authorization grant" flow, to get an access token. So **make sure to go to the API and Keys page in your admin account and uncheck "This is a mobile app"**. I know this checkbox is confusing, because you actually wanna build a mobile app... the point is authorization grant flow is supported for both mobile and non-mobile applications, and this checkbox should be renamed to "I will use implicit grant".

For more information about this OAuth flow see https://docs.docusign.com/esign/guide/authentication/oa2_auth_code.html.

**Comment by larrykluger** [comment]
But for your actual application, please use the implicit grant flow. The Authorization code grant flow is not secure for mobile applications.

Thank you!

**Comment by RaziaSandhu** [comment]
I have unchecked the  "This is a mobile app" checkBox but still have  same error message

**Comment by RaziaSandhu** [comment]
I just not get error message now but one another problem is occurred.

06-30 15:40:21.710 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/home
06-30 15:40:35.794 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/#/home
06-30 15:40:36.416 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/home#/home
06-30 15:40:57.381 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/#/home#%2Fhome
06-30 15:41:00.522 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/home#/home#%2Fhome
06-30 15:41:39.457 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/#/home#%2Fhome%23%2Fhome
06-30 15:41:41.289 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/home#/home#%2Fhome%23%2Fhome
06-30 15:42:05.474 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/#/home#%2Fhome%23%2Fhome%23%2Fhome
06-30 15:42:06.756 5326-5326/com.docusign.sample E/url: https://appdemo.docusign.com/home#/home#%2Fhome%23%2Fhome%23%2Fhome


It loads page in loop

**Comment by LarryKlugerDS** [comment]
Try deleting cookies

**Comment by RaziaSandhu** [comment]
I have cleared cookies but still the same thing occurring.

**Comment by mmallis87** [comment]
@RaziaSandhu does that happen after you put in the username and password and submit?

You should add some debugger breakpoint and find where the issue is. Once you figure out what's wrong then we will be able to tell how to fix your issue.

I'm suspecting that your redirect_uri to be incorrect. Try to log the full login url at this position: https://github.com/docusign/docusign-android-starter-kit/blob/0d4061dbed37419ed921095f6d667ad4599d3198/samples/embedded-signing/src/main/java/com/docusign/sample/LoginActivity.java#L95

If you're using "dsmomentum://oauth/callback", as the callback_uri, then that needs to be added to the definition of the integrator key (clientId) that you're using. Api and Keys page is where you can edit the key information.

**Comment by RaziaSandhu** [comment]
I'm really did not figure this out.  When I used login url on chrome its working well. I got this page on home and it loads again and again.
Can you help me please?

![screenshot_20170703-114133 1](https://user-images.githubusercontent.com/28975231/27780115-bc86d352-5fe4-11e7-9c6f-b753124dd445.png)

**Comment by mmallis87** [comment]
@RaziaSandhu it will be helpful if you can share with me your settings such redirect_uri and any other relevant information (no need to share the integrator key or secret). I really think your handling of the callback uri is somehow inaccurate.

**Comment by RaziaSandhu** [comment]
I solved the problem, but i don't understand that it works just as simple docusign website works:  Sign in and send documents. I never redirect to Sign and Send activity.

**Comment by kak00n** [comment]
@RaziaSandhu Could you tell me how you resolved the problem? I have the same problem ( loads page in loop). 
I think that my redirect_uri is incorrect, but i don´t know what url i must write. Now i put this ( https://account-d.docusign.com )

Could anyone help me?

Thanks!

**Comment by RaziaSandhu** [comment]
@kak00n   I have created login url as follows:
  Uri uri = Uri.parse(Config.OAUTH_BASE_URL + "oauth/auth?\n" +
                "response_type=code\n" +
                "&scope=all\n" +
                "&client_id=" + Config.CLIENT_ID +
                "&state=a39fh23hnf23\n" +
                "&redirect_uri=" + Config.PARAMETER_CALLBACK);

**Comment by RaziaSandhu** [comment]
I have added redirect_uri my company's website url

**Comment by RaziaSandhu** [comment]
https://account-d.docusign.com   is auth base url for demo accounts.

**Comment by RaziaSandhu** [comment]
I have added a bunch of classes in my project to make DocuSign work properly. Let me know if you need help.

**Comment by sri-harsha-g** [comment]
@RaziaSandhu Hi RaziaSandhu. I am also working on trying to run the "docusign-android-starter-kit" repo by following the steps mentioned in the readme document but I am unable to get pass the login screen.

Steps I have followed are as follows. 
1. Updated the client_id in the Config.java file as per the integrator key value.
2. Updated the login uri the way you have suggested in the Login Screen.

I am still not able to Login to the application and the following error displayed.
![image](https://user-images.githubusercontent.com/5960253/57778254-47a3af80-7741-11e9-86bd-13efc5f205e5.png)

Do you have a sample code which you can share for reference? Please do share any kind of guidance you can give me on this.
